# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# do i need to add the file endpoint here?

GET http://127.0.0.1:8000/files/
Accept: multipart/form-data


GET http://127.0.0.1:8000/user/
Accept: multipart/form-data

